/**
 * Hand-maintained TypeScript types for the Supabase database.
 * Regenerate via: supabase gen types typescript --project-id <id> > src/lib/database.types.ts
 */

export interface Database {
  public: {
    Tables: {
      files: {
        Row: {
          /** UUID primary key, generated by gen_random_uuid() */
          id: string
          /** UUID reference to auth.users — owner of the file */
          user_id: string
          /** File name including extension, e.g. "main.ts" */
          name: string
          /** File content — defaults to empty string */
          content: string
          /** Language identifier, e.g. "typescript", "python" — defaults to "text" */
          language: string
          /** Soft-delete flag — true means the file is hidden from the list */
          is_deleted: boolean
          /** ISO 8601 timestamp of soft-deletion, or null when not trashed */
          deleted_at: string | null
          /** ISO 8601 timestamp — set by DB default */
          created_at: string
          /** ISO 8601 timestamp — auto-updated by trigger on every UPDATE */
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          content?: string
          language?: string
          is_deleted?: boolean
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          content?: string
          language?: string
          is_deleted?: boolean
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'files_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      public_links: {
        Row: {
          /** UUID primary key */
          id: string
          /** UUID reference to files(id) */
          file_id: string
          /** UUID reference to auth.users(id) — owner of the link */
          user_id: string
          /** Unique hex token used in the public share URL */
          token: string
          /** ISO 8601 expiry timestamp, or null for no expiry */
          expires_at: string | null
          /** bcrypt hash of the access password, or null if no password */
          password_hash: string | null
          /** What the recipient is allowed to do */
          permission: 'view' | 'view+download'
          /** ISO 8601 creation timestamp */
          created_at: string
        }
        Insert: {
          id?: string
          file_id: string
          user_id: string
          token?: string
          expires_at?: string | null
          password_hash?: string | null
          permission?: 'view' | 'view+download'
          created_at?: string
        }
        Update: {
          file_id?: string
          user_id?: string
          token?: string
          expires_at?: string | null
          password_hash?: string | null
          permission?: 'view' | 'view+download'
        }
        Relationships: [
          {
            foreignKeyName: 'public_links_file_id_fkey'
            columns: ['file_id']
            isOneToOne: false
            referencedRelation: 'files'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'public_links_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      get_shared_file: {
        Args: { p_token: string; p_password: string | null }
        Returns: Record<string, unknown>
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
